# Generated by Django 6.1 on 2026-09-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
    ]
